// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package protobuf;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string pwd = 2;</code>
   */
  java.lang.String getPwd();
  /**
   * <code>string pwd = 2;</code>
   */
  com.google.protobuf.ByteString
      getPwdBytes();
}
