// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package protobuf;

public interface LogoutOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Logout)
    com.google.protobuf.MessageOrBuilder {
}
