// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package protobuf;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>int32 code = 2;</code>
   */
  int getCode();
}
